version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: voter-cache
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'

  poll-api:
    image: poll-api-basic:v1
    container_name: poll-api-1
    restart: always
    environment:
      - REDIS_URL=cache:6379
    ports:
      - '1080:1080'
    depends_on:
      - cache

  voter-api:
    image: voter-api-basic:v1
    container_name: voter-api-1
    restart: always
    environment:
      - REDIS_URL=cache:6379
    ports:
      - '1081:1080'
    depends_on:
      - cache

  votes-api:
    image: votes-api-basic:v1
    container_name: votes-api-1
    restart: always
    environment:
      - REDIS_URL=cache:6379
    ports:
      - '1082:3080'
    depends_on:
      - cache

